Parameters:
  ModelArtifactUrl:
    Type: String
    Description: S3 URL of the model artifact
  ContainerImage:
    Type: String
    Description: ECR image URL for the model container

Resources:
  SageMakerModel:
    Type: 'AWS::SageMaker::Model'
    Properties:
      ExecutionRoleArn: !GetAtt SageMakerRole.Arn
      ModelName: !Sub 'my-model-${AWS::StackName}'
      PrimaryContainer:
        Image: !Ref ContainerImage
        ModelDataUrl: !Ref ModelArtifactUrl

  SageMakerEndpointConfig:
    Type: 'AWS::SageMaker::EndpointConfig'
    Properties:
      EndpointConfigName: !Sub 'my-endpoint-config-${AWS::StackName}'
      ProductionVariants:
        - InitialInstanceCount: 1
          InstanceType: ml.m5.large
          ModelName: !Ref SageMakerModel
          VariantName: 'AllTraffic'

  SageMakerEndpoint:
    Type: 'AWS::SageMaker::Endpoint'
    Properties:
      EndpointName: !Sub 'my-endpoint-${AWS::StackName}'
      EndpointConfigName: !Ref SageMakerEndpointConfig

  InferenceLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub 'inference-lambda-${AWS::StackName}'
      Runtime: python3.8
      Code:
        ZipFile: |
          # Lambda function code to call SageMaker endpoint
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT_NAME: !Ref SageMakerEndpoint

  APIGatewayRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub 'my-project-API-${AWS::StackName}'

  APIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt APIGatewayRestAPI.RootResourceId
      PathPart: 'predict'

  APIGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref APIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: LAMBDA
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:$AWS::Region:lambda:path/2015-03-31/functions/${InferenceLambda.Arn}/invocations'

  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      StageName: prod

  APIGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      StageName: prod
      DeploymentId: !Ref APIGatewayDeployment